import test from 'node:test';
import assert from 'node:assert/strict';
import {createRoom,player,start,resolve,view,echo,tick} from '../lib/game.ts';
function room(n=3){const r=createRoom('ABCDEF',player(crypto.randomUUID(),'P0',1000));for(let i=1;i<n;i++)r.players.push(player(crypto.randomUUID(),'P'+i,1000));start(r,1000);return r;}
test('valid boards have distinct safe starts and reachable Source for 3–8 players',()=>{for(let n=3;n<=8;n++)for(let k=0;k<40;k++){const r=room(n);assert.equal(r.hazards.length,6);assert.equal(new Set(r.players.map(p=>p.x+','+p.y)).size,n);const blocked=new Set(r.hazards.map(p=>p.x+','+p.y));const seen=new Set();const q=[r.source];for(let i=0;i<q.length;i++){const p=q[i],key=p.x+','+p.y;if(seen.has(key))continue;seen.add(key);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const x=p.x+dx,y=p.y+dy;if(x>=0&&x<9&&y>=0&&y<9&&!seen.has(x+','+y)&&!blocked.has(x+','+y))q.push({x,y});}}for(const p of r.players){assert.ok(seen.has(p.x+','+p.y));assert.ok(Math.abs(p.x-r.source.x)+Math.abs(p.y-r.source.y)>=4);}assert.equal(r.budget,6*n);}});
test('projection reveals neither positions nor tokens nor teammate choices',()=>{const r=room();r.players[1].action='west';const v=view(r,r.players[0].id,1000);const s=JSON.stringify(v);for(const key of ['"x":','"y":','"source":','"hazards":','"token":'])assert.ok(!s.includes(key));assert.equal(v.players[1].ready,true);assert.ok(!s.includes('west'));});
test('hazard and boundary reject moves; only hazard costs budget',()=>{const r=room();r.hazards=[{x:2,y:1}];Object.assign(r.players[0],{x:1,y:1,action:'east'});Object.assign(r.players[1],{x:0,y:0,action:'north'});r.players[2].action='hold';resolve(r,2000);assert.equal(r.budget,17);assert.equal(r.players[0].x,1);assert.equal(r.players[1].y,0);assert.match(r.players[1].history[0],/boundary/);});
test('arrival win takes priority over exhausted reserve',()=>{const r=room();r.source={x:4,y:4};r.hazards=[{x:8,y:8}];r.budget=1;Object.assign(r.players[0],{x:3,y:4,action:'east'});Object.assign(r.players[1],{x:4,y:3,action:'south'});r.players[2].action='signal';resolve(r,2000);assert.equal(r.phase,'won');assert.equal(r.budget,0);assert.equal(r.score,146);});
test('scarce signals follow rotating priority without negative reserve',()=>{const r=room();r.round=2;r.budget=1;r.players.forEach(p=>p.action='signal');resolve(r,2000);assert.equal(r.players[1].echoes.length,1);assert.equal(r.players[0].echoes.length,0);assert.equal(r.budget,0);assert.equal(r.phase,'lost');});
test('pause stops resolution; timeout holds; round 24 ends',()=>{const r=room();r.paused=true;tick(r,99999);assert.equal(r.round,1);r.paused=false;tick(r,99999);assert.equal(r.round,2);assert.match(r.players[0].history[0],/held/);r.round=24;resolve(r,100000);assert.equal(r.phase,'lost');});
test('echo bands monotonic and hazard interference distinguishes near cells',()=>{const r=room();r.source={x:0,y:0};r.hazards=[{x:4,y:4}];const p=r.players[0];for(const [x,y,tone]of [[8,8,'scattered'],[8,0,'faint'],[5,0,'gathering'],[3,0,'clear'],[1,0,'radiant']]){Object.assign(p,{x,y});assert.equal(echo(r,p).tone,tone);}Object.assign(p,{x:4,y:3});assert.equal(echo(r,p).hazard,'fractured');Object.assign(p,{x:4,y:2});assert.equal(echo(r,p).hazard,'uneasy');});
