"use client";
import {useEffect,useRef,useState} from "react";
import type {PublicRoom,Action,Echo} from "@/lib/game";
import {Dialog,DialogContent,DialogDescription,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
const symbols=["◇","△","○","□","✧","⬡","⊕","☆"];
const toneNames={scattered:"Scattered",faint:"Faint",gathering:"Gathering",clear:"Clear",radiant:"Radiant"};
function Halo({echo,small=false}:{echo?:Echo;small?:boolean}){return <div role="img" aria-label={echo?toneNames[echo.tone]+" Source echo; "+echo.hazard+" hazard interference":"No signal emitted yet"} className={"orb "+(small?"small ":"")+(echo?echo.tone+" "+echo.hazard:"unknown")}><i/><i/><i/><b>{echo?"✦":"·"}</b></div>}
function Rules(){return <Dialog><DialogTrigger asChild><button className="subtle">How to play ↗</button></DialogTrigger><DialogContent className="rules"><DialogTitle>Find the Source. Together.</DialogTitle><DialogDescription>3–8 players. One invisible world. One shared reserve.</DialogDescription><ol><li><strong>Gather your team.</strong> Share your room code and stay on a voice call. The host starts when 3–8 players have joined.</li><li><strong>Choose one action per round.</strong> Move one cell north, east, south, or west for free; emit a signal for one shared charge; or hold. Lock it in. Choices are private and resolve together when everyone is ready, or after 30 seconds. Missing choices become holds. The host can pause for discussion.</li><li><strong>Read the echo.</strong> Scattered → faint → gathering → clear → radiant means closer to the Source. Amber interference means a hazard is nearby; jagged interference is the strongest warning. Compare your last three echoes with your team. Echoes describe where you were when you emitted them.</li><li><strong>Navigate carefully.</strong> The hidden board is 9 × 9 with fixed compass directions. You start on a distinct safe cell at least four steps from the Source. Six hazard cells reject your move and cost the team one charge. Boundary moves are also rejected, with a private cue. Players can share cells.</li><li><strong>Reach the Source.</strong> Arrival is automatic and announced. Arrived players stay there and help the others. A strict majority wins: 2 of 3; 3 of 4–5; 4 of 6–7; 5 of 8.</li></ol><p>You start with six charges per player, pooled together. You lose at zero charges or after round 24. Arrival wins take priority in the same round. Hazard costs resolve before signal costs; scarce signals are funded in rotating player order. Unfunded signals become holds.</p><p><strong>Team score:</strong> 100 for winning + 5 per unused charge + 2 per unused round. No individual rankings. Rooms expire after 24 hours. Keep this tab to reconnect as yourself.</p></DialogContent></Dialog>}
export default function Home(){
 const [name,setName]=useState(""),[code,setCode]=useState(""),[room,setRoom]=useState<PublicRoom|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[connected,setConnected]=useState(true),[now,setNow]=useState(Date.now()),[selected,setSelected]=useState<Action>("signal"),[replay,setReplay]=useState<{name:string;echo:Echo}|null>(null),[copied,setCopied]=useState(false);
 const token=useRef(""),roomRef=useRef<PublicRoom|null>(null),offset=useRef(0),pending=useRef(false);
 function accept(r:PublicRoom){if(roomRef.current?.code===r.code&&r.revision<roomRef.current.revision)return;offset.current=r.serverNow-Date.now();roomRef.current=r;setRoom(r);setConnected(true);sessionStorage.setItem("signal-room",r.code);setCode(r.code);}
 async function request(body?:Record<string,unknown>,joinCode?:string){const res=await fetch(body?"/api/room":"/api/room?code="+encodeURIComponent(joinCode??roomRef.current?.code??""),{method:body?"POST":"GET",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token.current},...(body?{body:JSON.stringify(body)}:{}),cache:"no-store"});const result=await res.json() as PublicRoom & {error?:string};if(!res.ok)throw Error(result.error??"Connection interrupted.");return result;}
 async function command(op:string,extra:Record<string,unknown>={}){if(pending.current)return;pending.current=true;setBusy(true);setError("");try{const r=await request({op,code:roomRef.current?.code??code,name,...extra});accept(r);return r;}catch(e){setError(e instanceof Error?e.message:"Unable to connect. Please retry.");}finally{pending.current=false;setBusy(false);}}
 useEffect(()=>{token.current=sessionStorage.getItem("signal-token")??crypto.randomUUID();sessionStorage.setItem("signal-token",token.current);const saved=sessionStorage.getItem("signal-room");const invite=new URLSearchParams(location.search).get("room");if(invite)setCode(invite.toUpperCase().slice(0,6));if(saved&&(!invite||saved===invite.toUpperCase())){setCode(saved);request(undefined,saved).then(accept).catch(()=>setError("Your previous room could not be restored. Join again or create a room."));}let stopped=false;let timer:ReturnType<typeof setTimeout>;async function poll(){if(roomRef.current&&!pending.current){try{const r=await request();if(!stopped)accept(r);}catch{if(!stopped)setConnected(false);}}if(!stopped)timer=setTimeout(poll,1200);}timer=setTimeout(poll,1200);const clock=setInterval(()=>setNow(Date.now()),250);return()=>{stopped=true;clearTimeout(timer);clearInterval(clock);};},[]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:"read_signal_room",description:"Read your current Signal room, shared echoes, reserve, and your private movement history. Does not expose the map.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).length)throw Error("This tool accepts an empty object only.");return roomRef.current??{phase:"not_joined"};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const me=room?.players.find(p=>p.id===room.me.id),host=room?.host===room?.me.id;
 const seconds=room?Math.max(0,Math.ceil((room.paused?room.remaining:room.deadline-now-offset.current)/1000)):0;
 const latest=me?.echoes.at(-1);
 async function copy(){try{await navigator.clipboard.writeText(location.origin+"/?room="+room!.code);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setError("Copy this room code to invite your team: "+room!.code);}}
 return <main className="shell"><header><a className="brand" href="/">◉ SIGNAL</a><div className="header-actions">{room&&<span className={"connection "+(!connected?"offline":"")}>{connected?"● Connected":"◌ Reconnecting…"}</span>}<Rules/></div></header>
 {error&&<p role="alert" className="error">{error}</p>}
 {!room?<section className="entry"><div className="intro"><p className="eyebrow">3–8 PLAYERS · ONE SHARED DESTINATION</p><h1>Lost, together.<br/><em>Found, together.</em></h1><p>No map. No coordinates. Just a signal.<br/>Listen to each other. Find the Source.</p><div className="orb"><i/><i/><i/><b>✦</b></div></div><section className="panel"><p className="eyebrow">ESTABLISH A CONNECTION</p><h2>Find your people.</h2><label>Your callsign<input autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?" maxLength={20}/></label><button className="primary" disabled={busy||!name.trim()} onClick={()=>command("create")}>{busy?"Connecting…":"Create a room ↗"}</button><div className="divider">OR JOIN AN EXPEDITION</div><form onSubmit={e=>{e.preventDefault();command("join");}}><label>Room code<input className="code-input" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z]/g,"").slice(0,6))} placeholder="ABCDEF" maxLength={6} autoCapitalize="characters" autoComplete="off" spellCheck={false}/></label><button className="wide" disabled={busy||!name.trim()||code.length!==6}>Join room →</button></form><p className="fine">Everyone plays on their own device.<br/>Stay on a voice call to compare your signals.</p></section></section>:
 <><div className="room-heading"><div><p className="eyebrow">EXPEDITION {room.phase==="lobby"?"LOBBY":"IN PROGRESS"}</p><h1>Room <span className="room-code">{room.code}</span></h1></div><button className="subtle" onClick={copy}>{copied?"Link copied ✓":"Copy invite link ↗"}</button></div>
 {room.phase==="lobby"?<section className="lobby-grid"><div className="panel"><p className="eyebrow">YOUR CREW · {room.players.length}/8</p><div className="crew-list">{room.players.map((p,i)=><div className="crew-row" key={p.id}><span className="symbol">{symbols[i]}</span><span>{p.name}{p.id===room.me.id?" (you)":""}</span><small>{p.id===room.host?"Host":p.online?"Connected":"Away"}</small></div>)}{Array.from({length:Math.max(0,3-room.players.length)},(_,i)=><div className="crew-row waiting" key={i}><span className="symbol">+</span>Waiting for a player…</div>)}</div>{host?<button className="primary" disabled={busy||room.players.length<3||!connected} onClick={()=>command("start")}>{room.players.length<3?"Waiting for "+(3-room.players.length)+" more…":"Begin expedition →"}</button>:<p className="fine">Your host will begin when everyone is ready.</p>}<p className="fine">Share the code or invite link. No account needed.</p></div><div className="brief"><Halo/><h2>Separate paths.<br/><em>A shared destination.</em></h2><p>Each of you starts somewhere unknown. Spend signals to feel your way toward the Source. Talk, compare, and take the next step together.</p><div className="brief-stats"><div><strong>{room.players.length*6}</strong><span>shared charges</span></div><div><strong>24</strong><span>rounds to find it</span></div><div><strong>{room.required}</strong><span>arrivals to win</span></div></div></div></section>:
 <><div className="stats"><div><span>ROUND</span><strong>{String(room.round).padStart(2,"0")} <small>/ 24</small></strong></div><div><span>SIGNAL RESERVE</span><strong className={room.budget<6?"warning":""}>{room.budget} <small>charges</small></strong></div><div><span>AT THE SOURCE</span><strong>{room.players.filter(p=>p.arrived).length} <small>/ {room.required} needed</small></strong></div><div><span>{room.paused?"DISCUSSION PAUSE":"NEXT RESOLUTION"}</span><strong>{room.phase==="playing"?(room.paused?"Paused":seconds+"s"):"Complete"}</strong></div></div>
 {(room.phase==="won"||room.phase==="lost")&&<section className={"result "+room.phase} role="status"><p className="eyebrow">{room.phase==="won"?"CONNECTION COMPLETE":"SIGNAL LOST"}</p><h2>{room.phase==="won"?"You found each other.":"Every echo taught you something."}</h2><p>{room.reason} {room.phase==="won"?"Team score: "+room.score:room.players.filter(p=>p.arrived).length+" of "+room.required+" required players arrived."}</p>{host?<button className="primary" disabled={busy} onClick={()=>command("lobby")}>Return to lobby →</button>:<p className="fine">The host can return everyone to the lobby for another expedition.</p>}</section>}
 <section className="game-grid"><section className="panel controls"><div className="section-head"><p className="eyebrow">YOUR TRANSMITTER</p><span>{symbols[room.players.findIndex(p=>p.id===room.me.id)]} {me?.name}</span></div><Halo echo={latest}/><div className="echo-caption"><strong>{latest?toneNames[latest.tone]:"Uncharted"}</strong><span>{latest?"Last emitted in round "+latest.round+" · "+(latest.hazard==="quiet"?"No interference":latest.hazard==="uneasy"?"Amber interference":"Jagged interference"):"Emit a signal to sense your surroundings"}</span></div>
 {room.phase==="playing"&&(me?.arrived?<div className="arrived"><h3>You’re at the Source.</h3><p>Stay on the call. Help your crew find the way.</p></div>:<><div className="compass" role="group" aria-label="Choose your direction">{(["north","west","hold","east","south"] as Action[]).map(a=><button key={a} className={a+" "+(selected===a?"selected":"")} disabled={!!room.me.action||room.paused||busy} onClick={()=>setSelected(a)} aria-pressed={selected===a} aria-label={a==="hold"?"Hold position":"Move "+a}>{a==="north"?"↑":a==="south"?"↓":a==="east"?"→":a==="west"?"←":"·"}<small>{a==="hold"?"HOLD":a.slice(0,1).toUpperCase()}</small></button>)}</div><button className={"signal-choice "+(selected==="signal"?"selected":"")} aria-pressed={selected==="signal"} disabled={!!room.me.action||room.paused||busy} onClick={()=>setSelected("signal")}><span>◉ Emit a signal</span><small>1 shared charge</small></button><button className="primary" disabled={busy||!!room.me.action||room.paused||!connected} onClick={()=>command("action",{action:selected,round:room.round,game:room.game})}>{room.paused?"Paused for discussion":room.me.action?"Locked: "+room.me.action+" ✓":"Lock in "+selected+" →"}</button><p className="fine center">{room.players.filter(p=>p.ready||p.arrived).length} of {room.players.length} players ready · movement is free</p></>)}
 {host&&room.phase==="playing"&&<button className="subtle" disabled={busy||!connected} onClick={()=>command("pause")}>{room.paused?"Resume round →":"Pause for discussion"}</button>}
 </section><section className="team-area"><div className="section-head"><h2>Your crew’s echoes</h2><span className="eyebrow">COMPARE. DISCUSS. MOVE.</span></div><div className="echo-grid">{room.players.map((p,i)=><article className="echo-card" key={p.id}><div className="section-head"><strong><span className="mini-symbol">{symbols[i]}</span> {p.name}</strong><span className={"player-status "+(p.arrived?"at-source":"")}>{p.arrived?"At Source":p.ready?"Ready":p.online?"Choosing":"Away"}</span></div><Halo echo={p.echoes.at(-1)} small/><p className="center">{p.echoes.length?toneNames[p.echoes.at(-1)!.tone]:"No echo yet"}</p><div className="replays">{p.echoes.map(e=><button key={e.round} className="subtle" onClick={()=>setReplay({name:p.name,echo:e})}>↺ R{e.round}</button>)}</div></article>)}</div><p className="fine">Echoes show the moment they were emitted, not current positions. Select a round to replay it.</p><div className="log-grid"><section className="log"><h3>Shared field notes</h3><ul>{room.events.slice(-8).reverse().map((e,i)=><li key={i}>{e}</li>)}</ul></section><section className="log"><h3>Your footsteps <span>PRIVATE</span></h3><ul>{room.me.history.length?room.me.history.slice(-8).reverse().map((e,i)=><li key={i}>{e}</li>):<li>Your movement history will appear here.</li>}</ul></section></div></section></section></>}
 {room.canClaimHost&&<button className="subtle" onClick={()=>command("claim")} disabled={busy}>Host is away · take over hosting</button>}
 </>}
 <footer>TRUST THE SIGNAL. TRUST EACH OTHER.<span>9 × 9 hidden world · 24 rounds</span></footer>
 <Dialog open={!!replay} onOpenChange={open=>{if(!open)setReplay(null);}}><DialogContent><DialogTitle>{replay?.name} · Round {replay?.echo.round}</DialogTitle><DialogDescription>A recorded echo. This describes the position at emission.</DialogDescription>{replay&&<><Halo key={replay.name+replay.echo.round} echo={replay.echo}/><p className="center">{toneNames[replay.echo.tone]} · {replay.echo.hazard==="quiet"?"No hazard interference":replay.echo.hazard==="uneasy"?"Amber interference":"Jagged interference"}</p></>}</DialogContent></Dialog>
 </main>;
}



