export type Action = "north" | "east" | "south" | "west" | "signal" | "hold";
export type Echo = { round:number; tone:"scattered"|"faint"|"gathering"|"clear"|"radiant"; hazard:"quiet"|"uneasy"|"fractured" };
export type Player = {id:string;token:string;name:string;x:number;y:number;arrived:boolean;action:Action|null;echoes:Echo[];history:string[];seen:number};
export type Room = {code:string;host:string;phase:"lobby"|"playing"|"won"|"lost";players:Player[];source:{x:number;y:number};hazards:{x:number;y:number}[];round:number;budget:number;deadline:number;paused:boolean;remaining:number;events:string[];score:number;reason:string;game:number};
export const actions:Action[]=["north","east","south","west","signal","hold"];
const delta={north:[0,-1],east:[1,0],south:[0,1],west:[-1,0]};
const same=(a:{x:number;y:number},b:{x:number;y:number})=>a.x===b.x&&a.y===b.y;
const distance=(a:{x:number;y:number},b:{x:number;y:number})=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const random=(n:number)=>crypto.getRandomValues(new Uint32Array(1))[0]%n;
const cell=()=>({x:random(9),y:random(9)});
export function player(token:string,name:string,now:number):Player{return{id:crypto.randomUUID(),token,name,x:0,y:0,arrived:false,action:null,echoes:[],history:[],seen:now};}
export function createRoom(code:string,p:Player):Room{return{code,host:p.id,phase:"lobby",players:[p],source:{x:0,y:0},hazards:[],round:0,budget:0,deadline:0,paused:false,remaining:30000,events:[],score:0,reason:"",game:0};}
export function required(r:Room){return Math.floor(r.players.length/2)+1;}
function reachable(r:Room){const seen=new Set<string>();const q=[r.source];for(let i=0;i<q.length;i++){const p=q[i];const key=p.x+","+p.y;if(seen.has(key))continue;seen.add(key);for(const [dx,dy]of Object.values(delta)){const n={x:p.x+dx,y:p.y+dy};if(n.x>=0&&n.x<9&&n.y>=0&&n.y<9&&!r.hazards.some(h=>same(h,n))&&!seen.has(n.x+","+n.y))q.push(n);}}return seen;}
export function start(r:Room,now:number){if(r.players.length<3||r.players.length>8)throw Error("Gather 3–8 players before starting.");r.source={x:random(5)+2,y:random(5)+2};r.hazards=[];while(r.hazards.length<6){const p=cell();if(distance(p,r.source)>1&&!r.hazards.some(h=>same(h,p)))r.hazards.push(p);}const reach=reachable(r);const starts=[];for(let y=0;y<9;y++)for(let x=0;x<9;x++)if(reach.has(x+","+y)&&distance({x,y},r.source)>=4)starts.push({x,y});if(starts.length<r.players.length)return start(r,now);for(const p of r.players){Object.assign(p,starts.splice(random(starts.length),1)[0]);p.arrived=false;p.action=null;p.echoes=[];p.history=[];}r.phase="playing";r.round=1;r.budget=6*r.players.length;r.deadline=now+30000;r.paused=false;r.remaining=30000;r.events=["Expedition started. Choose a direction or share your first signal."];r.reason="";r.score=0;r.game++;}
export function echo(r:Room,p:Player):Echo{const d=distance(p,r.source);const h=Math.min(...r.hazards.map(h=>distance(h,p)));return{round:r.round,tone:d<=1?"radiant":d<=3?"clear":d<=5?"gathering":d<=8?"faint":"scattered",hazard:h===1?"fractured":h===2?"uneasy":"quiet"};}
export function resolve(r:Room,now:number){if(r.phase!=="playing"||r.paused)return;const events:string[]=[];for(const p of r.players){if(p.arrived)continue;const a=p.action??"hold";if(a in delta){const [dx,dy]=delta[a as keyof typeof delta];const n={x:p.x+dx,y:p.y+dy};if(n.x<0||n.x>8||n.y<0||n.y>8)p.history.push(`Round ${r.round}: ${a} — boundary; stayed put.`);else if(r.hazards.some(h=>same(h,n))){r.budget=Math.max(0,r.budget-1);p.history.push(`Round ${r.round}: ${a} — collision; stayed put.`);events.push(`${p.name} hit a hazard. One charge lost.`);}else{Object.assign(p,n);p.history.push(`Round ${r.round}: moved ${a}.`);if(same(p,r.source)){p.arrived=true;events.push(`${p.name} reached the Source!`);}}}else if(a==="hold")p.history.push(`Round ${r.round}: held position.`);}
// Rotating priority makes scarce-signal allocation deterministic and fair.
for(let i=0;i<r.players.length;i++){const p=r.players[(i+r.round-1)%r.players.length];if(p.action!=="signal"||p.arrived)continue;if(r.budget>0){r.budget--;p.echoes.push(echo(r,p));p.echoes=p.echoes.slice(-3);p.history.push(`Round ${r.round}: emitted a signal.`);events.push(`${p.name} emitted a signal.`);}else p.history.push(`Round ${r.round}: signal unfunded; held position.`);}
for(const p of r.players)p.action=null;
r.events=[...r.events,...events,`Round ${r.round} resolved.`].slice(-40);
if(r.players.filter(p=>p.arrived).length>=required(r)){r.phase="won";r.score=100+5*r.budget+2*(24-r.round);r.reason="You found the Source, together.";}else if(r.budget===0||r.round===24){r.phase="lost";r.reason=r.budget===0?"The signal reserve is empty.":"The final round has passed.";}else{r.round++;r.deadline=now+30000;}}
export function tick(r:Room,now:number){if(r.phase==="playing"&&!r.paused&&(now>=r.deadline||r.players.every(p=>p.arrived||p.action)))resolve(r,now);}
export function view(r:Room,id:string,now:number,revision=0){const me=r.players.find(p=>p.id===id)!;return{revision,code:r.code,host:r.host,phase:r.phase,round:r.round,budget:r.budget,deadline:r.deadline,paused:r.paused,remaining:r.remaining,events:r.events,score:r.score,reason:r.reason,game:r.game,required:required(r),serverNow:now,me:{id:me.id,action:me.action,history:me.history},players:r.players.map(p=>({id:p.id,name:p.name,arrived:p.arrived,ready:!!p.action,echoes:p.echoes,online:now-p.seen<20000})),canClaimHost:now-(r.players.find(p=>p.id===r.host)?.seen??0)>60000};}
export type PublicRoom=ReturnType<typeof view>;

